export const defaultGiftContent = {
  header: {
    brand: "The Movement",
    ctaText: "Membership",
  },
  stickyBar: {
    label: "Continue With Roye",
    price: "From $20/month",
    ctaText: "View Options",
  },
  gate: {
    eyebrow: "YOUR FREE MOVEMENT RESET",
    headline: "UNLOCK YOUR 5-MINUTE PRACTICE",
    subheadline: "Experience how Roye combines mobility, strength, and control in one guided, equipment-free practice.",
    benefitLine: "5–7 minutes · No equipment · Suitable for all levels",
    emailPlaceholder: "Enter your email address",
    ctaText: "UNLOCK MY FREE PRACTICE",
    microcopy: "Get instant access and a copy delivered to your inbox.",
    marketingLabel: "Yes, send me movement guidance, new practices, and membership updates from Roye Gold.",
    gateImage: "",
  },
  hero: {
    eyebrow: "YOUR FREE MOVEMENT RESET",
    headline: "YOU'RE IN. LET'S MOVE.",
    supporting: "In the next few minutes, Roye will guide you through a full-body practice that brings mobility, strength, and control together—no equipment required.",
    primaryCta: "START THE 5-MINUTE PRACTICE",
    secondaryCta: "Explore Full Membership",
  },
  introVideo: {
    headline: "BEFORE YOU BEGIN",
    thumbnailLabel: "A MESSAGE FROM ROYE",
    duration: "60 SECONDS",
    youtubeUrl: "",
    videoUrl: "",
    poster: "",
  },
  prep: {
    items: [
      { title: "5–7 MINUTES", desc: "Move at your own pace." },
      { title: "NO EQUIPMENT", desc: "Just a little space around you." },
      { title: "ALL LEVELS", desc: "No previous experience required." },
    ],
  },
  practice: {
    eyebrow: "YOUR FREE PRACTICE",
    headline: "THE 5-MINUTE MOVEMENT RESET",
    supporting: "Follow along with Roye as he guides you through a short full-body sequence combining mobility, strength, coordination, and control.",
    thumbnailLabel: "YOUR 5-MINUTE MOVEMENT RESET",
    thumbnailSub: "Follow along with Roye",
    duration: "5–7 MINUTES",
    youtubeUrl: "",
    videoUrl: "",
    poster: "",
  },
  closing: {
    headline: "NOTICE WHAT CHANGED",
    supporting: "Take a moment to notice your breathing, your range of motion, and how connected your body feels.",
    ctaText: "CONTINUE PRACTICING WITH ROYE",
    youtubeUrl: "",
    videoUrl: "",
    poster: "",
  },
  bridge: {
    eyebrow: "READY TO GO FURTHER?",
    headline: "MAKE THIS A DAILY PRACTICE",
    copy: "What you experienced in a few minutes is only the beginning. The Movement gives you a guided daily practice, structured progression, and Roye's complete method for developing greater mobility, strength, and control over time.",
    cards: [
      { title: "DAILY GUIDANCE", desc: "Know exactly what to practice each day." },
      { title: "A COMPLETE METHOD", desc: "Build mobility, strength, and control together." },
      { title: "CONTINUOUS PROGRESSION", desc: "Follow a clear structure that develops over time." },
    ],
    ctaText: "SEE MEMBERSHIP OPTIONS",
  },
  primaryTestimonial: {
    quote: "After years of feeling restricted through my hips and lower back, I began moving with much more confidence within my first month.",
    name: "Daniel",
    context: "Member since 2025",
    img: "",
  },
  membership: {
    annual: {
      badge: "MOST POPULAR",
      title: "Annual Membership",
      price: "$20",
      period: "/ month",
      billingNote: "Billed annually at $240",
      description: "Build a consistent practice with Roye's complete method, ongoing content, and weekly guidance from The Movement team.",
      benefits: [
        "Full access to daily practices",
        "Weekly live community call",
        "Exclusive ongoing content",
        "Structured mobility and strength progression",
        "Access to The Movement community",
      ],
      cta: "CONTINUE WITH ANNUAL MEMBERSHIP",
      microcopy: "Immediate access to the complete membership.",
    },
    monthly: {
      title: "Monthly Membership",
      price: "$35",
      period: "/ month",
      billingNote: "Billed monthly",
      description: "Full access to The Movement with the flexibility of monthly billing.",
      benefits: [
        "Full access to daily practices",
        "Mobility, strength, and control programming",
        "New sessions added regularly",
        "Access to The Movement community",
      ],
      cta: "CONTINUE MONTH TO MONTH",
      microcopy: "Cancel any time before your next billing date.",
    },
  },
  testimonials: {
    heading: "What Members Are Experiencing",
    items: [
      { quote: "[TESTIMONIAL 1]", name: "[MEMBER NAME 1]", context: "", img: "" },
      { quote: "[TESTIMONIAL 2]", name: "[MEMBER NAME 2]", context: "", img: "" },
    ],
  },
  faq: {
    heading: "Questions Before You Begin?",
    items: [
      { q: "Is this suitable for beginners?", a: "Yes. The Movement is designed to help people work from their current level. Roye provides guidance and options so that members can gradually build mobility, strength, coordination, and control." },
      { q: "How much time do I need each day?", a: "Practices vary in length, but the program is designed to make consistent movement realistic within a busy schedule. Members can select practices based on the time they have available." },
      { q: "Do I need any equipment?", a: "Many practices require little or no equipment. When equipment is recommended, it will be clearly identified before the practice begins." },
      { q: "What should I do if I have an injury or physical limitation?", a: "Listen to your body and avoid movements that cause pain. The Movement is not a substitute for personal medical advice, diagnosis, or rehabilitation. Consult a qualified healthcare professional where appropriate." },
      { q: "What is included, and how do monthly and annual membership differ?", a: "Both plans include access to The Movement's core digital membership. The annual plan is billed once per year and offers the best monthly value. The monthly plan is billed every month and can be cancelled before the next billing date." },
    ],
  },
  final: {
    headline: "CONTINUE PRACTICING WITH ROYE",
    copy: "You have experienced the first few minutes. Membership gives you the structure, variety, guidance, and progression to make Roye's method part of your daily life.",
    primaryCta: "BEGIN ANNUAL MEMBERSHIP",
    secondaryCta: "CHOOSE MONTHLY MEMBERSHIP",
    returnLink: "Not ready? Return to your free practice.",
  },
  footer: {
    brand: "The Movement by Roye Gold",
    copyright: "© {year} The Movement by Roye Gold. All rights reserved.",
  },
};