export const defaultHandstandContent = {
  navbar: {
    brandName: "Handstand",
    navCtaText: "Enroll Now",
  },
  hero: {
    eyebrow: "Master the Handstand",
    headline1: "Master Your",
    headline2: "Handstand In",
    headlineAccent: "4 Stages",
    boldDescription: "Handstands are a skill, not a talent.",
    subheadline: "A clear, four-stage video path that takes you from your first wall hold to advanced balance work. Each phase builds on the last — with bonus challenges once you've mastered the basics.",
    ctaText: "Enroll Now",
    ctaSubtext: "One-time payment · Lifetime access",
    imageUrl: "https://media.base44.com/images/public/6a0c583766eb003a373061f3/77f6a616e_generated_image.png",
  },
  whatYouGet: {
    headline: "What you get",
    items: [
      "All 4 phases — Wall hold to freestanding",
      "2 bonus libraries: Elements + Toolbox",
      "Lifetime access — no subscription",
    ],
  },
  showcase: {
    headline: "See It In Action",
    subheadline: "Watch how the method works — from your first kick-up to a wall-free hold.",
    videoUrl: "",
    youtubeUrl: "",
    posterUrl: "",
    posterAspect: "horizontal",
  },
  problem: {
    eyebrow: "The Struggle",
    headline: "Why Most People Never Hold a Handstand",
    subtitle: "Sound familiar?",
    points: [
      { title: "Fear of Falling", desc: "You freeze every time you kick up, worried about crashing down." },
      { title: "Wall Dependency", desc: "You can hold against the wall, but the moment you step away, it all falls apart." },
      { title: "No Clear Progression", desc: "YouTube tutorials give random tips with no path from A to Z." },
      { title: "Inconsistent Practice", desc: "Without a plan, you practice sporadically and never see real progress." },
    ],
  },
  solution: {
    eyebrow: "The Solution",
    headline: "A Structured Path to Wall-Free Handstands",
    subtitle: "The Handstand Blueprint breaks the skill into digestible weekly progressions.",
    imageUrl: "https://images.unsplash.com/photo-1574680096145-d05b474e2155?auto=format&fit=crop&w=900&q=80",
    videoUrl: "",
    videoLabel: "Watch the method",
    videoDuration: "2:14",
    statValue: "8wks",
    statLabel: "to wall-free",
    benefits: [
      { title: "8-Week Progression", desc: "Follow a clear, week-by-week roadmap from complete beginner to wall-free holds." },
      { title: "Strength Foundations", desc: "Build the wrist, shoulder, and core strength needed to support your bodyweight." },
      { title: "Balance Mechanics", desc: "Master the micro-adjustments and fingertip control that keep you upside down." },
      { title: "Daily Practice Plan", desc: "Know exactly what to do each day — no guessing, no wasted sessions." },
    ],
  },
  curriculum: {
    eyebrow: "What's Inside",
    headline: "8 Weeks to Your First Hold",
    subtitle: "Each week builds on the last, taking you from ground zero to confident wall-free handstands.",
    modules: [
      { week: "Week 1", title: "Foundations & Wrist Prep", desc: "Strengthen wrists, shoulders, and build the foundational positions." },
      { week: "Week 2", title: "Wall Fundamentals", desc: "Learn proper wall entries, exits, and holds with correct alignment." },
      { week: "Week 3", title: "Building Hold Time", desc: "Progressively increase your wall hold duration and endurance." },
      { week: "Week 4", title: "Balance Mechanics", desc: "Shift weight, learn fingertip control, and find your balance point." },
      { week: "Week 5", title: "Wall-Free Progressions", desc: "Begin stepping away from the wall with safe bail techniques." },
      { week: "Week 6", title: "The Kick-Up", desc: "Master controlled kick-ups and consistent entries." },
      { week: "Week 7", title: "Wall-Free Holds", desc: "Put it all together for your first unassisted holds." },
      { week: "Week 8", title: "Refinement & Beyond", desc: "Clean up your form and learn pathways to advanced skills." },
    ],
  },
  instructor: {
    eyebrow: "Your Coach",
    name: "Roye Gold",
    title: "Movement Coach",
    bio: "Roye Gold has spent over a decade teaching movement, strength, and body control. After helping thousands of students build mobility and strength through The Movement, he's distilled the handstand learning process into a clear, repeatable system. No fluff — just what works.",
    imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=800&q=80",
  },
  testimonials: {
    eyebrow: "Student Wins",
    headline1: "Real Students.",
    headlineAccent: "Real Results.",
    subtitle: "See how students transformed their practice with the Handstand Blueprint.",
    items: [
      { name: "Sarah M.", role: "Yoga Teacher", quote: "I tried learning handstands for 2 years on my own. This course got me to my first 10-second wall-free hold in 6 weeks.", img: "", videoUrl: "" },
      { name: "James K.", role: "Fitness Enthusiast", quote: "The progression is so clear. Every week I could feel myself getting closer. By week 7, I held my first handstand.", img: "", videoUrl: "" },
      { name: "Lisa R.", role: "Beginner", quote: "As a complete beginner, I was terrified of falling. The bail techniques alone were worth the price.", img: "", videoUrl: "" },
    ],
    stats: [
      { value: "6wks", label: "to first wall-free hold" },
      { value: "500+", label: "students trained" },
      { value: "4.9", label: "avg rating" },
    ],
  },
  pricing: {
    eyebrow: "Enroll Today",
    lockInTitle: "Lock In Our Lowest Price",
    lockInSubtitle: "Pre-order now. Be first in line when we go live.",
    headline: "Get Full Access",
    subtitle: "One-time payment. Lifetime access. Start today.",
    price: "14.99",
    priceNote: "One-time payment",
    badge: "Best Value",
    features: [
      "8-week structured progression",
      "40+ video lessons",
      "Daily practice plans",
      "Wall-free bail techniques",
      "Strength & mobility drills",
      "Lifetime access",
      "Mobile-friendly format",
      "Future updates included",
    ],
    ctaText: "Enroll Now",
    guarantee: "30-day money-back guarantee",
    annualCardTitle: "The Handstand Course is included free",
    annualCardTitleAccent: "+ Roye's entire library",
    annualCardDescription: "Go annual and the full Handstand Course is yours at no extra cost — alongside 240+ guided sessions, weekly live coaching, and every new release. One membership, Roye's complete method.",
  },
  faq: {
    eyebrow: "Questions",
    headline: "Frequently Asked Questions",
    items: [
      { q: "Do I need any prior experience?", a: "No. The course is designed for complete beginners and progresses step by step from day one." },
      { q: "How long do I have access?", a: "Lifetime access. Buy once and you can revisit the content whenever you want, including all future updates." },
      { q: "What equipment do I need?", a: "Just a wall and some floor space. No special equipment required." },
      { q: "How much time per day?", a: "The daily sessions are 15-30 minutes. Consistency matters more than duration." },
      { q: "Is there a guarantee?", a: "Yes — if you're not satisfied within 30 days, contact us for a full refund." },
    ],
  },
  finalCta: {
    eyebrow: "Start Today",
    headline: "Your First Wall-Free Handstand Starts Here",
    subtitle: "Stop guessing. Follow the blueprint and get upside down.",
    ctaText: "Enroll Now",
    priceNote: "One-time payment · Lifetime access · 30-day guarantee",
  },
  settings: {
    accentColor: "",
  },
};