export const defaultHandstandContent = {
  texts: {
    ctaPreLaunch: "Get the Handstand Course — $99",
    ctaRegular: "Get the Handstand Course — $149",
    secondaryCtaText: "View Purchase Options",
    microcopy: "One-time payment · Hosted on Skool · Access instructions sent by email",
    offerLabelPreLaunch: "PRE-LAUNCH PRICE",
    offerLabelRegular: "NOW AVAILABLE",
    preLaunchLabel: "PRE-LAUNCH ACCESS · SAVE $50 UNTIL AUGUST 2",
    deliveryNotePreLaunch: "Course access begins August 3",
    deliveryNoteRegular: "Access instructions delivered by email",
    heroCountdownLabel: "Pre-launch ends in",
    nextPriceNote: "$149 beginning August 3",
    alsoIncludedText: "Also included with Annual Membership",
    announcementLeftText: "PRE-LAUNCH PRICE ENDS AUGUST 2",
    announcementRightText: "$99 NOW · $149 FROM AUGUST 3",
    announcementCtaText: "GET THE COURSE",
    announcementNowAvailable: "NOW AVAILABLE",
    announcementOneTimePayment: "One-time payment",
    announcementCountdownLabel: "Pre-launch price ends in",
    announcementMobileEndsLabel: "· ENDS",
    stickyBarPreLaunch: "$99 until Aug 2",
    stickyBarRegular: "$149",
    stickyBarCtaText: "Get the Course",
    standalonePriceNotePreLaunch: "Pre-launch price · $149 beginning August 3",
    standalonePriceNoteRegular: "One-time payment",
    finalCtaPreLaunchReminder: "Pre-launch price: $99 until August 2",
    footerTerms: "Terms",
    footerPrivacy: "Privacy Policy",
    footerRefund: "Refund Policy",
    footerContact: "Contact",
    videoPlaceholder: "Add a video in the admin editor",
  },
  hero: {
    eyebrow: "THE MOVEMENT PRESENTS",
    preLaunchLabel: "PRE-LAUNCH ACCESS · SAVE $50 UNTIL AUGUST 2",
    headline1: "BUILD A STRONGER,",
    headline2: "MORE CONTROLLED HANDSTAND",
    supporting: "Roye Gold's eight-week course for beginners building toward their first wall-free hold—and experienced practitioners refining balance, alignment, and control.",
    imageUrl: "https://media.base44.com/images/public/6a0c583766eb003a373061f3/77f6a616e_generated_image.png",
  },
  authorityStrip: {
    items: [
      { stat: "10+ years", label: "teaching movement" },
      { stat: "Thousands", label: "of students coached" },
      { stat: "Workshops", label: "& training sessions" },
    ],
  },
  methodVideo: {
    headline: "SEE HOW ROYE TEACHES THE HANDSTAND",
    subheadline: "See how Roye's structured progression helps students build stronger foundations, reduce wall dependence, and develop greater balance and control.",
    overlayText: "Watch the 60-Second Course Preview",
    youtubeUrl: "",
    videoUrl: "",
    posterUrl: "",
    posterAspect: "horizontal",
  },
  midPageOffer: {
    line1: "Pre-order the complete Handstand Course for $99",
    line2: "Regular price $149 beginning August 3",
    line3: "One-time payment · Course access emailed August 3",
  },
  problem: {
    eyebrow: "THE CORE PROBLEM",
    headline: "MORE EFFORT ISN'T THE ANSWER. A BETTER PROGRESSION IS.",
    subtitle: "Most people do not struggle because they are incapable of learning a handstand. They struggle because they repeat isolated drills without a clear sequence.",
    points: [
      { title: "STUCK AT THE WALL", desc: "You can hold with support, but lose your position as soon as you move away." },
      { title: "FEAR OF FALLING", desc: "You hesitate during kick-ups because you have not learned how to exit safely." },
      { title: "NO CLEAR PROGRESSION", desc: "You collect drills and tips, but do not know what to practice next." },
    ],
    conclusion: "The course gives every drill a purpose, every practice a structure and every stage a clear next step.",
  },
  startFromLevel: {
    eyebrow: "WHEREVER YOU ARE STARTING",
    headline: "START FROM YOUR LEVEL",
    subtitle: "The course meets you at your current level and gives you the appropriate progression from there.",
    cards: [
      {
        title: "NEW TO HANDSTANDS",
        bullets: [
          "Prepare your wrists and shoulders",
          "Learn safe entries and exits",
          "Build alignment and upside-down confidence",
          "Progress from wall support toward independent balance",
        ],
      },
      {
        title: "ALREADY TRAINING HANDSTANDS",
        bullets: [
          "Cleaner alignment",
          "More controlled entries",
          "Greater balance and consistency",
          "Advanced variations where appropriate",
        ],
      },
    ],
  },
  curriculum: {
    eyebrow: "THE EIGHT-WEEK ROADMAP",
    headline: "YOUR EIGHT-WEEK HANDSTAND ROADMAP",
    subtitle: "Each week builds on the last, helping you develop the physical preparation, technique and control required for a stronger handstand.",
    stages: [
      {
        title: "STAGE 1 — BUILD THE FOUNDATION",
        weeks: "Weeks 1–2",
        summary: "Wrist preparation, alignment, safe wall entries, exits, and foundational holds.",
        modules: [
          { week: "Week 1", title: "Foundations & Wrist Preparation", desc: "Prepare the wrists and shoulders and establish the positions that support the rest of the course." },
          { week: "Week 2", title: "Wall Fundamentals", desc: "Learn controlled wall entries, exits and holds with stronger alignment." },
        ],
      },
      {
        title: "STAGE 2 — DEVELOP CONTROL",
        weeks: "Weeks 3–4",
        summary: "Build hold time, strength, endurance, fingertip control, and balance awareness.",
        modules: [
          { week: "Week 3", title: "Building Hold Time", desc: "Develop the strength, endurance and comfort required to spend more time upside down." },
          { week: "Week 4", title: "Balance Mechanics", desc: "Learn how weight shift, fingertip pressure and body position affect balance." },
        ],
      },
      {
        title: "STAGE 3 — MOVE AWAY FROM THE WALL",
        weeks: "Weeks 5–7",
        summary: "Practice safe exits, controlled kick-ups, reduced wall dependence, and wall-free holds.",
        modules: [
          { week: "Week 5", title: "Wall-Free Progressions", desc: "Begin reducing wall dependence through controlled drills and safe exit techniques." },
          { week: "Week 6", title: "The Kick-Up", desc: "Practice more repeatable entries and learn how to control the amount of force you use." },
          { week: "Week 7", title: "Wall-Free Holds", desc: "Bring the individual skills together and work toward controlled independent holds." },
        ],
      },
      {
        title: "STAGE 4 — REFINE YOUR HANDSTAND",
        weeks: "Week 8",
        summary: "Improve form and consistency and identify the right next progression for your level.",
        modules: [
          { week: "Week 8", title: "Refinement & Next Progressions", desc: "Improve form, diagnose weaknesses and identify the next progression for your level." },
        ],
      },
    ],
    callout: "Already comfortable upside down? Follow the advanced variations within the course to refine alignment, entries, balance and control.",
  },
  whatIsIncluded: {
    eyebrow: "WHAT IS INCLUDED",
    headline: "EVERYTHING YOU NEED TO TRAIN WITH A PLAN",
    items: [
      "Complete eight-week progression",
      "Guided video lessons",
      "Structured practice plans",
      "Safe entries and exit techniques",
      "Beginner and advanced variations",
      "Dedicated Skool course access",
    ],
  },
  purchaseOptions: {
    eyebrow: "PURCHASE OPTIONS",
    headline: "CHOOSE HOW YOU WANT TO TRAIN",
    subtitle: "Purchase the Handstand Course on its own, or access it as part of Roye's complete annual membership.",
    standalone: {
      label: "STANDALONE COURSE",
      title: "THE HANDSTAND COURSE",
      features: [
        "Complete eight-week course",
        "Guided lessons and practice plans",
        "Beginner and advanced progressions",
        "Dedicated access through Skool",
        "Access instructions emailed August 3",
      ],
      microcopy: "One-time payment · No subscription",
    },
    annual: {
      eyebrow: "ONGOING TRAINING",
      title: "THE MOVEMENT ANNUAL MEMBERSHIP",
      priceMonthly: "$20/month",
      priceNote: "Billed annually at $240",
      valueStatement: "Includes the Handstand Course, Roye's complete Movement library, ongoing member programming, and live member sessions.",
      features: [
        "Handstand Course included while membership remains active",
        "Full Movement training library",
        "Ongoing member programming",
        "Live member sessions",
      ],
      ctaText: "Choose Annual Membership",
      disclosure: "Handstand Course access remains available while your Annual Membership is active.",
    },
  },
  instructor: {
    eyebrow: "YOUR COACH",
    headline: "TAUGHT BY ROYE GOLD",
    bio: "Roye Gold has spent years teaching movement, strength and body control to students at different levels. This course distills his handstand teaching into a structured system that students can follow independently, one progression at a time.",
    imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=800&q=80",
  },
  socialProof: {
    headline: "PROGRESS BUILT THROUGH PRACTICE",
    subtitle: "Real students. Real progress.",
    items: [],
  },
  faq: {
    eyebrow: "FAQ",
    headline: "FREQUENTLY ASKED QUESTIONS",
    items: [
      { q: "IS THIS COURSE SUITABLE FOR COMPLETE BEGINNERS?", a: "Yes. The course begins with wrist preparation, body position, wall fundamentals and safe exit techniques before progressing toward wall-free balance." },
      { q: "WHAT IF I ALREADY HAVE SOME HANDSTAND EXPERIENCE?", a: "The course also includes progressions for students who already train handstands and want to improve alignment, entries, balance, control and consistency." },
      { q: "WHEN WILL I RECEIVE ACCESS?", a: "The course launches on Monday, August 3, 2026. Standalone purchasers will receive their Skool access instructions by email.", aPost: "Access instructions are delivered by email following purchase." },
      { q: "WHERE IS THE COURSE HOSTED?", a: "The course is hosted on a dedicated Handstand Course page within Skool." },
      { q: "WHAT EQUIPMENT DO I NEED?", a: "You need a wall and some floor space. A mat is recommended for comfort during floor-based drills." },
      { q: "HOW MUCH TIME SHOULD I PRACTICE?", a: "Sessions are designed to be short and consistent. Plan for 15–30 minutes per practice, a few times per week." },
      { q: "HOW LONG DO STANDALONE PURCHASERS HAVE ACCESS?", a: "Standalone purchasers receive ongoing access to the dedicated Handstand Course page after the one-time purchase." },
      { q: "HOW DOES ACCESS WORK WITH AN ANNUAL MEMBERSHIP?", a: "The course is included as part of your Annual Membership. You retain access while your membership remains active. If your membership ends, your Skool and Handstand Course access also ends." },
      { q: "CAN I REQUEST A REFUND?", a: "Purchases are non-refundable except where required by applicable law." },
    ],
  },
  finalCta: {
    eyebrow: "START TODAY",
    headline: "BUILD YOUR HANDSTAND WITH A CLEAR PLAN",
    subtitle: "Stop collecting random drills. Follow a structured eight-week progression designed to meet you at your current level.",
    microcopy: "One-time payment · Hosted on Skool · Access instructions sent by email",
  },
  footer: {
    brand: "The Movement by Roye Gold",
    copyright: "© 2026 The Movement by Roye Gold. All rights reserved.",
  },
  settings: {
    accentColor: "",
  },
};